#!/bin/dash

LOG_TAG="[Restart Macbook TouchBarServer]"

# Option parsing
for arg in "$@"
do
    case $arg in
        --version)
            echo "1.0.0"
            exit 0
            ;;
        *)
            # Handling for unknown options
            logger -s "$LOG_TAG Error: Unknown option $arg"
            exit 201
            ;;
    esac
done

# Error if not running with root privileges
if [ "$(id -u)" -ne 0 ]; then
    logger -s "$LOG_TAG Error: This script must be run as root"
    exit 103
fi

# Get the process ID of the TouchBarServer process
old_pid=$(pgrep TouchBarServer)

# If TouchBarServer is not found
if [ -z "$old_pid" ]; then
    logger -s "$LOG_TAG TouchBarServer not found."
    exit 101
fi

# Force termination if the process exists
echo "$LOG_TAG Restarting TouchBarServer(old PID=$old_pid)"
logger "$LOG_TAG Restarting TouchBarServer(old PID=$old_pid)"
kill -TERM $old_pid

# Check the result of the kill command
if [ $? -ne 0 ]; then
    logger -s "$LOG_TAG Failed to restart TouchBarServer. (kill failed)"
    exit 102
fi

# Confirm restart
sleep 5 # Wait for the process to terminate and start anew
new_pid=$(pgrep TouchBarServer)
if [ -z "$new_pid" ]; then
    logger -s "$LOG_TAG Failed to restart TouchBarServer. (no new process found)"
    exit 103
elif [ "$new_pid" -eq "$old_pid" ]; then
    logger -s "$LOG_TAG Failed to restart TouchBarServer. (old process still running)"
    exit 104
fi

echo "$LOG_TAG Successfully restarted TouchBarServer. (old PID=$old_pid, new PID=$new_pid)"
logger "$LOG_TAG Successfully restarted TouchBarServer. (old PID=$old_pid, new PID=$new_pid)"
